### ISSUE TITLE
Label descriptions exceed maximum length

### ISSUE THREAD

**Issue by henrist** [seantrane/github-label-presets#63]
A GitHub label can have a description of maximum 100 characters.

Example of labels that are exceeding that limit as of this writing:

- `state: pending` with 129 chars
- `state: inactive` with 120 chars
- `type: chore` with 103 chars

Using the latest version of https://github.com/Financial-Times/github-label-sync gives `422: Validation Failed` error when including these labels.

The feature of pushing descriptions to GitHub was added this summer in https://github.com/Financial-Times/github-label-sync/pull/19

**Comment by arcnmx** [comment]
stalebot, you are a scourge upon github

**Comment by seantrane** [comment]
after neglecting this repo for while, it is now updated. apologies.
